<a href="https://colab.research.google.com/github/ROARMarketingConcepts/Cornell_ML_Course/blob/main/Matrix_Multiplication_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.random.random((2,3))
Y = np.random.random((3,2))
X,Y

(array([[0.69481812, 0.79930268, 0.11838642],
        [0.19897707, 0.59857723, 0.77285065]]),
 array([[0.97362015, 0.86535753],
        [0.54574708, 0.50642892],
        [0.19746469, 0.26868858]]))

In [3]:
X@Y

array([[1.13608317, 1.03786517],
       [0.67301057, 0.68297927]])

In [4]:
X=np.random.random((3,2))
Y=np.random.random((2,4))
np.dot(X,Y)


array([[0.0533417 , 0.18984203, 0.21998608, 0.18289472],
       [0.05920542, 0.41239267, 0.20035175, 0.30549042],
       [0.10488804, 0.41282152, 0.42398039, 0.3797205 ]])

In [5]:
X = np.random.random((9,4))
X

array([[0.86849895, 0.02511165, 0.28674931, 0.36293098],
       [0.1389903 , 0.38308187, 0.67105934, 0.46446255],
       [0.4030807 , 0.91720625, 0.46330097, 0.9950233 ],
       [0.32463622, 0.3649676 , 0.48543133, 0.36636874],
       [0.07737139, 0.77786019, 0.00409969, 0.32239361],
       [0.60599051, 0.83112248, 0.35697069, 0.89018686],
       [0.17361725, 0.37145329, 0.16116042, 0.49585936],
       [0.37495032, 0.86056036, 0.66089904, 0.95695217],
       [0.73215427, 0.78486372, 0.2198699 , 0.67968894]])

Multiply a matrix by a scalar

In [6]:
3*X

array([[2.60549685, 0.07533496, 0.86024794, 1.08879294],
       [0.41697089, 1.14924561, 2.01317803, 1.39338766],
       [1.20924211, 2.75161874, 1.3899029 , 2.9850699 ],
       [0.97390866, 1.0949028 , 1.456294  , 1.09910621],
       [0.23211417, 2.33358057, 0.01229906, 0.96718082],
       [1.81797154, 2.49336744, 1.07091208, 2.67056058],
       [0.52085176, 1.11435988, 0.48348127, 1.48757807],
       [1.12485096, 2.58168109, 1.98269712, 2.87085652],
       [2.19646281, 2.35459116, 0.65960969, 2.03906683]])

In [7]:
np.dot(3,X)

array([[2.60549685, 0.07533496, 0.86024794, 1.08879294],
       [0.41697089, 1.14924561, 2.01317803, 1.39338766],
       [1.20924211, 2.75161874, 1.3899029 , 2.9850699 ],
       [0.97390866, 1.0949028 , 1.456294  , 1.09910621],
       [0.23211417, 2.33358057, 0.01229906, 0.96718082],
       [1.81797154, 2.49336744, 1.07091208, 2.67056058],
       [0.52085176, 1.11435988, 0.48348127, 1.48757807],
       [1.12485096, 2.58168109, 1.98269712, 2.87085652],
       [2.19646281, 2.35459116, 0.65960969, 2.03906683]])

In [8]:
X = np.random.random((5,6))
Y = np.random.random((6,1))
X,Y

(array([[0.99339115, 0.1436463 , 0.80182409, 0.14112316, 0.14876582,
         0.68886537],
        [0.89778172, 0.23022413, 0.58315596, 0.33860552, 0.16068683,
         0.66495109],
        [0.6592888 , 0.09165374, 0.85692692, 0.96046724, 0.71464913,
         0.31459503],
        [0.07450486, 0.42370647, 0.26735118, 0.44303764, 0.18254121,
         0.00398353],
        [0.16514418, 0.62194738, 0.55111645, 0.54535479, 0.71553646,
         0.35852975]]),
 array([[0.00982524],
        [0.00313838],
        [0.07425289],
        [0.7010518 ],
        [0.31722065],
        [0.83819298]]))

In [9]:
X@Y, np.dot(X,Y)

(array([[0.79327724],
        [0.89855499],
        [1.23412471],
        [0.39375052],
        [0.9543185 ]]),
 array([[0.79327724],
        [0.89855499],
        [1.23412471],
        [0.39375052],
        [0.9543185 ]]))

#### Multiplying Row Vectors

The `np.dot()` function expects matrices to have compatible dimensions. Using the `np.outer()` function automatically transposes the first matrix before computing the product. Because the first matrix is transposed, the order of vectors matters.

In [12]:
X=np.random.random((1,6))
Y=np.random.random((1,4))
X,Y

(array([[0.81970116, 0.10503094, 0.716929  , 0.07940752, 0.11712332,
         0.30165158]]),
 array([[0.06653698, 0.6347418 , 0.31910353, 0.71968093]]))

In [13]:
np.dot(X,Y)

ValueError: ignored

In [16]:
np.outer(X,Y)

array([[0.05454044, 0.52029859, 0.26156953, 0.58992329],
       [0.00698844, 0.06666753, 0.03351574, 0.07558876],
       [0.04770229, 0.45506481, 0.22877458, 0.51596013],
       [0.00528354, 0.05040327, 0.02533922, 0.05714808],
       [0.00779303, 0.07434307, 0.03737447, 0.08429142],
       [0.02007098, 0.19147087, 0.09625808, 0.21709289]])

#### Multiplying Column Vectors

In [17]:
X=np.random.random((6,1))
Y=np.random.random((4,1))
X,Y

(array([[0.02694362],
        [0.67476273],
        [0.03351051],
        [0.02503724],
        [0.62211919],
        [0.10410773]]),
 array([[0.01968999],
        [0.27212835],
        [0.2708256 ],
        [0.45001748]]))

In [18]:
np.outer(X,Y)

array([[0.00053052, 0.00733212, 0.00729702, 0.0121251 ],
       [0.01328607, 0.18362206, 0.18274302, 0.30365502],
       [0.00065982, 0.00911916, 0.0090755 , 0.01508031],
       [0.00049298, 0.00681334, 0.00678073, 0.0112672 ],
       [0.01224952, 0.16929627, 0.1684858 , 0.27996451],
       [0.00204988, 0.02833066, 0.02819504, 0.0468503 ]])