<a href="https://colab.research.google.com/github/ROARMarketingConcepts/Cornell_ML_Course/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array([[1,2,3],[4,5,6]])
X, X.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [ ]:
X.ndim, X.size

(2, 6)

In [ ]:
npvec = np.array([1,2,3])
npvec.shape    #  the array is indexed by a single index from 0 to 2.

(3,)

In [ ]:
colvec = npvec.reshape((3,1))
colvec, colvec.shape

(array([[1],
        [2],
        [3]]),
 (3, 1))

#### Instructions

1.   Create a NumPy vector $\vec{v_1}$ that contains $([3,4,5])$ using the `np.array()` function.
2.   `print()` the vector $\vec{v_1}$ to confirm we’ve correctly created the vector.

3. `print()` the vector’s shape `v1.shape`. We should find that its shape is $(3,)$

4. Using the function `.reshape()`, reshape the $\vec{v_1}$ NumPy vector into a column vector $\vec{v_2}$  by changing the shape to $(3,1)$

5. `print()` $\vec{v_2}$  to confirm our data is stored in a column vector.

6. Reshape the $\vec{v_1}$ NumPy vector into a row vector $\vec{v_3}$ by changing the shape to $(1,3)$.

7. `print()` $\vec{v_3}$ to confirm our data is stored in a row vector.

In [ ]:
v1=np.array([3,4,5])
v1,v1.shape

(array([3, 4, 5]), (3,))

In [ ]:
v2=v1.reshape(3,1)
v2, v2.shape

(array([[3],
        [4],
        [5]]),
 (3, 1))

In [ ]:
v3=v1.reshape(1,3)
v3, v3.shape

(array([[3, 4, 5]]), (1, 3))

In [ ]:
v1+v2  # v2 is not in the correct format, so the result is incorrect.

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

In [ ]:
v4=v2.flatten()
v4, v4.shape

(array([3, 4, 5]), (3,))

In [ ]:
v1+v4

array([ 6,  8, 10])

#### Creating Common Matrices
There are also a few functions in NumPy for creating common matrices:

`np.eye()` creates an identity matrix

`np.zeros()` creates a matrix of all zeros

`.arange()` creates a vector of equally spaced values

In [ ]:
np.eye(3), np.eye(5)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))

In [ ]:
np.arange(10), np.arange(1,10,2), np.arange(2,10,2)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 5, 7, 9]),
 array([2, 4, 6, 8]))

#### Multiplication

To perform matrix multiplication, use `np.dot()` or the $@$ symbol. For example, we could multiply matrices $X$ and $Y$ by writing either `np.dot(X,Y)` or $X @ Y$.

In [ ]:
X = np.array([[1,2], [3,4]])
Y = np.array([[5,6],[7,8]])
A = np.array([[1,2,3,4], [7,8,9,10]])
B = np.array([[4,5,6,7], [1,2,3,4]])

In [ ]:
X,Y,A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 1,  2,  3,  4],
        [ 7,  8,  9, 10]]),
 array([[4, 5, 6, 7],
        [1, 2, 3, 4]]))

In [ ]:
np.dot(X,Y)

array([[19, 22],
       [43, 50]])

In [ ]:
X@Y

array([[19, 22],
       [43, 50]])

In [ ]:
A@B  # matrices are mismatched dimensionally

ValueError: ignored

In [ ]:
A@B.T

array([[ 60,  30],
       [192,  90]])

In [ ]:
np.dot(A,np.transpose(B))

array([[ 60,  30],
       [192,  90]])

Use NumPy to calculate:  $AB^T−Y$


In [ ]:
A@B.T-Y

array([[ 55,  24],
       [185,  82]])

#### Other Matrix Operations

Other useful functions we will use in our projects are `np.amax()`, `np.amin()`, `np.argmax()`, `np.argmin()`, and `np.sum(X)`. With all of these functions, we can specify the axis along which we want to perform the operation. If no axis is specified, the functions will perform the operation across all dimensions. Here are some examples of these functions in use:

Largest element in $X$: 	`np.amax(X)`

Largest elements along the first axis: 	`np.amax(X, axis = 0)`

Smallest element in $X$:	`np.amin(X)`

Smallest elements along the second axis:	`np.amin(X, axis = 1)`

Index of the smallest element in $X$:	`np.argmin(X)`

Indices of the largest elements along the first axis:	`np.argmax(X, axis = 0)`

Sum of all elements in $X$:	`np.sum(X)`

Sum of elements along the first axis:`np.sum(X, axis = 0)`

Sort the matrix (in ascending order) along the last axis (axis=-1):	`np.sort(D)`

Sort the matrix along the first axis:	`np.sort(D, axis=0)`

Indices for sorting matrix (in ascending order) along the last axis (axis=-1):	`np.argsort(D)`

Indices for sorting matrix along the first axis:	`np.argsort(D, axis=0)`


In [ ]:
Y

array([[5, 6],
       [7, 8]])

In [ ]:
np.amax(Y)  # largest element in Y

8

In [ ]:
np.amin(Y, axis=0)

array([5, 6])

In [ ]:
np.amin(Y, axis=1)

array([5, 7])

In [ ]:
np.argmax(Y,axis=0)

array([1, 1])

In [ ]:
np.argmax(Y,axis=1)

array([1, 1])

In [ ]:
np.argmin(Y,axis=0)

array([0, 0])

In [ ]:
np.argmin(Y,axis=1)

array([0, 0])

In [ ]:
np.sum(Y,axis=0)

array([12, 14])

In [ ]:
np.sum(Y,axis=1)

array([11, 15])

In [ ]:
np.sort(Y,axis=-1)

array([[5, 6],
       [7, 8]])

#### Find Multiple Smallest Values

We learned how to find the index for the smallest value for each row in a matrix. We might need the $n$ lowest values in a row rather than simply the lowest. In this exercise, we will find the three smallest values for each row in a matrix. This is useful when we are implementing $k$ nearest neighbors, when $k>=1$.

In [ ]:
D = np.array([[1, 4, 8, 5],[4, 8, 2, 9],[2, 0, 4, 5]])
D

array([[1, 4, 8, 5],
       [4, 8, 2, 9],
       [2, 0, 4, 5]])

Find the indexes for the three lowest values for each row.

In [ ]:
sorted = np.argsort(D, axis=1)
sorted

array([[0, 1, 3, 2],
       [2, 0, 1, 3],
       [1, 0, 2, 3]])

In [ ]:
sorted = sorted[:,:3]
sorted

array([[0, 1, 3],
       [2, 0, 1],
       [1, 0, 2]])

Also,

In [ ]:
sorted = np.argsort(D, axis=1)[:,:3]
sorted

array([[0, 1, 3],
       [2, 0, 1],
       [1, 0, 2]])

#### Adding Columns and Rows to Matrices

The `np.vstack` and `np.hstack` functions can be used to add columns or rows to existing matrices.

In [ ]:
X,Y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [ ]:
np.vstack((X,Y)), np.vstack((Y,X))

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[5, 6],
        [7, 8],
        [1, 2],
        [3, 4]]))

In [ ]:
np.hstack((X,Y)), np.hstack((Y,X))

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 array([[5, 6, 1, 2],
        [7, 8, 3, 4]]))

**Exercise:** Find the maximum elements in $A$ along the first axis `(axis = 0)` and add it to the sum of elements in $B$ along the first axis.

In [ ]:
maxA=np.max(A,axis=0)
A, maxA

(array([[ 1,  2,  3,  4],
        [ 7,  8,  9, 10]]),
 array([ 7,  8,  9, 10]))

In [ ]:
B

array([[4, 5, 6, 7],
       [1, 2, 3, 4]])

In [ ]:
result=np.sum(np.vstack((maxA,B)),axis=0)
result

array([12, 15, 18, 21])

#### Element-wise Matrix Operations

There are many operations that we might want to perform, such as taking the square root or exponent on each element of a NumPy array. Some examples of these functions are `np.exp()`, `np.sqrt()`, and `np.square()`. There are many NumPy functions that will perform element-wise operations on NumPy arrays. Refer to the official documentation for more information.


In [ ]:
Z=np.arange(0,10,1)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.exp(Z)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sqrt(Z)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.square(Z)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### Indexing and Slicing

NumPy arrays can be indexed and sliced, just like Python’s list. Let’s explore indexing and slicing on 1-D and multidimensional arrays.

In [ ]:
x1 = np.arange(2,12,2)
x1, x1[3], x1[1:3], x1[-2:]

(array([ 2,  4,  6,  8, 10]), 8, array([4, 6]), array([ 8, 10]))

In [ ]:
type(x1[3]), type(x1[1:3])

(numpy.int64, numpy.ndarray)

In [ ]:
x2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x2[::],x2[0,2]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 3)

In [ ]:
x2[1:,:2],x2[0],x2[:,0]

(array([[4, 5],
        [7, 8]]),
 array([1, 2, 3]),
 array([1, 4, 7]))

In [ ]:
for row in x2:
  print(row)

[1 2 3]
[4 5 6]
[7 8 9]


**Exercise:** Return only the third and fourth column of matrix $A$

In [ ]:
A

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [ ]:
A[:,2:4]

array([[ 3,  4],
       [ 9, 10]])